### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by imexception** [leonHua/LGank#1]
加载的时候还可以刷新，
刚点两下就崩了
java.lang.IllegalStateException: An instance of OnFlingListener already set.
                                                   at android.support.v7.widget.SnapHelper.setupCallbacks(SnapHelper.java:114)
                                                   at android.support.v7.widget.SnapHelper.attachToRecyclerView(SnapHelper.java:102)
                                                   at com.leon.lgank.fragment.HomeGirlFragment.onClick(HomeGirlFragment.java:106)

**Comment by leonHua** [comment]
你好，能描述下具体的操作流程吗？是只在福利这个界面出错？还有机型和系统版本能提供一下吗，我这边用的红米note目前没发现问题，谢谢

**Comment by leonHua** [comment]
已经修复，欢迎继续使用
